create sequence company_sequence start 1;

create table if not exists company(
  id     bigint generated by default as identity,
  company_name    varchar(255) not null
);

create sequence employee_sequence start 1;

create table if not exists employee(
  id     bigint generated by default as identity,
  name   varchar(255) not null,
  age    int,
  salary double,
  company_id int,
  foreign KEY (company_id) references company(id)
);